config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users

  get 'simple_pages/products'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  root 'simple_pages#index'
  post 'payments/create'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true #Adds validation to the Product model。

	has_many :orders
	has_many :comments, dependent: :destroy

	def self.search(search_term)
		if Rails.env.production? # use "ilike" matching operator for postgres to ignore upper- and lower-case
			Product.where("name ilike ?", "%#{search_term}%")
		else
			Product.where("name LIKE ?", "%#{search_term}%")
		end
	end

	def highest_rating_comment
		comments.rating_desc.first
	end

	def lowest_rating_comment
		comments.rating_asc.first
	end

	def average_rating
  		comments.average(:rating).to_f
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end 

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)    
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = @products
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end
 

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <%= render comment %>
        <!--div>
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            	<% if signed_in? && current_user.admin? %>
			    <%= link_to ('<span class="fas fa-trash"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
  				<% end %>
        	</p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div> -->
    <% end %>
</div>


app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-12">  

    <%= form_with(model: product, local: true) do |form| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>         

      <div class="form-group">
        <div class="control-label col-sm-2">      
          <%= form.label :name %>
        </div>
        <div class="col-sm-8">
          <%= form.text_field :name, class: "form-control", placeholder: "name of bike", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2"> 
          <%= form.label :description %>
        </div>
        <div class="col-sm-8">
          <%= form.text_area :description, rows: 6, class: "form-control", placeholder: "Description" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2"> 
          <%= form.label :image_url %>
        </div>
        <div class="col-sm-8">
          <%= form.text_field :image_url, class: "form-control", placeholder: "URL", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2"> 
          <%= form.label :colour %>
        </div>
        <div class="col-sm-8">
          <%= form.text_field :colour, class: "form-control", placeholder: "colour", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= form.label :price %>
        </div>
        <div class="col-sm-8">
          <%= form.text_field :price, class: "form-control", placeholder: "price", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>


    <% end %>
  </div>
</div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <div class='rating'></div>
    </p>    
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="col-sm-6 col-md-4">
    <div  class="productgallery-image"><%= image_tag(product.image_url, class: "img-fluid") %></div>
    <div class="productgallery-info">
      <a href="#"><h2><%= product.name %></h2></a>
      <p><%= product.description %></p>
      <p><%= product.colour %></p>
      <p><%= product.price %></p>
    </div>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', product %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="index-content">
  <h1>Products</h1>
    <div class="container-fluid">
      <div class="row">
        <% cache(cache_key_for_products) do %>
  			<%= render @products %>
		<% end %>
      </div>
      <div class="btn  product_create">
        <%= link_to 'New Product', new_product_path, :class => "new-product" %>
      </div>
    </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <section class="row" data-product-id="<%= @product.id %>">
    <div class="col-sm-6 img">
      <%= image_tag(@product.image_url, data_zoom_image: @product.image_url, class: "img-fluid img-zoom") %>
    </div>

    <section class="col-sm-6 products-info">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Colour:</strong>
        <%= @product.colour %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>

      <p>Average Rating: <div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> </p>

      <%= form_with(url: '/payments/create') do |form| %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <%= hidden_field_tag(:product_id, @product.id) %>
      <% end %>
      
      <p>
        <%= link_to 'Edit', edit_product_path(@product) %> 
        <%= link_to 'Back', products_path %>
      </p>
      <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
      <%= render 'new_comment' %>
      <%= render 'comments' %>
      <%= will_paginate @comments %>

    </section>
    <!-- /col-sm-6 -->
  </section>