config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "user_registrations" }

  resources :products do
    resources :comments
  end

  resources :users

  get 'simple_pages/products'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  root 'simple_pages#index'
  post 'payments/create'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders, only: [:index, :show, :create, :destroy]

  mount ActionCable.server => '/cable'
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; by  Carlos Pons
    </small>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark  fixed-top" role="navigation" id="navbar-example">
  <a class="navbar-brand"><%= link_to "Berbi", root_path, :class => current_class?(root_path) %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= form_with(url: products_path, method: 'get', class: "navbar-form", role: "search", local: true) do |form| %>
    <!--<%= form.label :q %> -->
    <%= form.text_field :q, id: 'q', value: params[:q] %>
    <%= form.submit 'Search', class: "btn btn-default" %>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Products", products_path, :class => current_class?(products_path)%>
      </li>
      <li class="nav-item">
        <%= link_to "About", simple_pages_about_path, :class => current_class?(simple_pages_about_path) %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", simple_pages_contact_path, :class => current_class?(simple_pages_contact_path)%>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to('Login', new_user_session_path, class: "nav-link") %>
      </li>
      <% end %>
      </li>
    </ul>
  </div>
</nav> <!-- end nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nameofapp</title>
 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>       
  
  </head>
  
  <body>

    <%= render 'layouts/navigation' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success success-note" role="alert"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger alert-note" role="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>